### PR TITLE
feat(server/framework): add qb-core and more formats

### PR DESCRIPTION
**Pull request by BerkieBb**
- Added qb-core support
- Added more formats for the playerGroup function
These are the formats you can use now
```lua
playerGroup(source, 'groupName') -- Single group check
playerGroup(source, {'group1', 'group2', 'groupetc'}) -- Array group check
playerGroup(source, {['group1'] = 1, ['group2'] = 5, ['groupetc'] = 0}) -- Table with group as index and value for rank/grade
```

### CODE REVIEW

**Comment by thelindat** [comment]
QB doesn't support these ace checks out-of-the-box though, does it?

So usual QB and ESX iteration would just be:
```lua
if type(job) == 'table' then
	local rank = job[xPlayer.job.name]
	if job and xPlayer.job.grade >= rankthen
		return true
	end
elseif job == xPlayer.job.name then
	return true
end

return false
```
Then support for job2 (because weirdos) and gang.


For Ox I can use the following, and groups are a generic catch-all that could refer to jobs, gangs, vip, license, etc.
```lua
function playerGroup(source, groups)
	if not groups then return true end
	local playerGroups = Player(source).getGroup()

	for group, rank in pairs(groups) do
		local playerRank = playerGroups[group]
		if playerRank and playerRank >= rank then
			return true
		end
	end
end
```



The ACL check in place at the moment is experimental and more like "hey, you can check groups without having to import the framework environment"; functionality it's the same as above.
```lua
function playerGroup(source, group)
	if not group then return true end

	for k, v in pairs(group) do
		if IsPlayerAceAllowed(source, ('group.%s:%s'):format(k, v)) then
			return true
		end
	end
end
```

The latter (IsPlayerAceAllowed) also performs better, up to about 5 ace checks (then the export comes ahead).
image
image

**Comment by BerkieBb** [comment]
> QB doesn't support these ace checks out-of-the-box though, does it?

It does now for the general permissions but job permissions aren't setup by default, so I'll change it to be the usual job check

**Comment by BerkieBb** [comment]
Changed it to job checks

**Comment by BerkieBb** [comment]
Let me actually change that to the simplified version and not allow arrays then

**Comment by thelindat** [comment]
Was a single click away from merging 😆

**Comment by BerkieBb** [comment]
Should be good now though

**Pull request merged**
