### PR TITLE
Added Show UI to door options

### PR DESCRIPTION
**Pull request by JoeSzymkowiczFiveM**
Was previously Show NUI in nui_doorlock. Hides UI elements for a door when the option is set to false.

### CODE REVIEW

**Comment by thelindat** [comment]
Would cause some confusion changing the default to hide the ui; I’d recommend swapping it around (hideUi).

**Comment by JoeSzymkowiczFiveM** [comment]
Did you have a preference about left or right column?

**Comment by thelindat** [comment]
No.

**Review by LukeWasTakenn — APPROVED** [review]
Centered the alignment for the checkbox, if there were to be another one added in the future the stacking would have to be changed a bit.

Overall UI side LGTM.

**Pull request merged**
